name: entity-disambiguation-ver2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd77b12b_0
  - absl-py=1.4.0=py310haa95532_0
  - aiofiles=22.1.0=py310haa95532_0
  - aiohttp=3.8.5=py310h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aiosqlite=0.18.0=py310haa95532_0
  - anyio=3.5.0=py310haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py310haa95532_0
  - attrs=23.1.0=py310haa95532_0
  - babel=2.11.0=py310haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py310haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py310haa95532_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.3.5=py310h9128911_0
  - box2d-py=2.3.8=py310h8a704f9_5
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2023.12.12=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=haedb8bc_5
  - certifi=2023.11.17=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.1.2=py310haa95532_0
  - contourpy=1.0.5=py310h59b6b97_0
  - cryptography=41.0.3=py310h3438e0d_0
  - cuda-cccl=12.3.101=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvcc=12.3.107=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - eigen=3.4.0=h2d74725_0
  - entrypoints=0.4=py310haa95532_0
  - exceptiongroup=1.0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=hd77b12b_0
  - farama-notifications=0.0.4=py310haa95532_0
  - ffmpeg=4.2.3=ha925a31_0
  - filelock=3.9.0=py310haa95532_0
  - flatbuffers=2.0.0=h6c2663c_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h9c4af85_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.3.3=py310h2bbff1b_0
  - fsspec=2023.9.2=py310haa95532_0
  - gast=0.4.0=pyhd3eb1b0_0
  - getopt-win32=0.1=h2bbff1b_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - google-auth=2.22.0=py310haa95532_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=hd77b12b_1
  - graphviz=2.50.0=h7eca76f_1
  - grpc-cpp=1.48.2=hf108199_0
  - grpcio=1.48.2=py310hf108199_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - gts=0.7.6=h63ab5a1_3
  - h5py=3.9.0=py310hfc34f40_0
  - harfbuzz=4.3.0=hb646838_1
  - hdf5=1.12.1=h51c971a_3
  - huggingface_hub=0.17.3=py310haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - inflect=5.3.0=py310haa95532_1
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.25.0=py310h9909e9c_0
  - ipython=8.15.0=py310haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py310haa95532_0
  - jax-jumpy=1.0.0=py310haa95532_0
  - jedi=0.18.1=py310haa95532_1
  - jinja2=3.1.2=py310haa95532_0
  - joblib=1.2.0=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py310haa95532_0
  - jupyter=1.0.0=py310haa95532_8
  - jupyter_client=7.4.9=py310haa95532_0
  - jupyter_console=6.6.3=py310haa95532_0
  - jupyter_core=5.3.0=py310haa95532_0
  - jupyter_events=0.6.3=py310haa95532_0
  - jupyter_server=1.23.4=py310haa95532_0
  - jupyter_server_fileid=0.9.0=py310haa95532_0
  - jupyter_server_ydoc=0.8.0=py310haa95532_1
  - jupyter_ydoc=0.2.4=py310haa95532_0
  - jupyterlab=3.6.3=py310haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py310haa95532_0
  - jupyterlab_widgets=3.0.5=py310haa95532_0
  - keras=2.10.0=py310haa95532_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py310hd77b12b_0
  - krb5=1.20.1=h5b6d351_1
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.4.107=0
  - libcurand-dev=10.3.4.107=0
  - libcurl=8.2.1=h86230a5_0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libgd=2.3.3=ha43c60c_1
  - libiconv=1.16=h2bbff1b_2
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=hb652d5d_1
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.10.0=hcd4344a_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxgboost=1.7.3=hd77b12b_0
  - libxml2=2.10.4=h0ad7f3c_1
  - libxslt=1.1.37=h2bbff1b_1
  - lightgbm=3.3.5=py310hd77b12b_0
  - lxml=4.9.3=py310h09808a7_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown=3.4.1=py310haa95532_0
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib=3.7.2=py310haa95532_0
  - matplotlib-base=3.7.2=py310h4ed8f06_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mistune=0.8.4=py310h2bbff1b_1000
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.8=py310h2bbff1b_0
  - mkl_random=1.2.4=py310h59b6b97_0
  - mpmath=1.3.0=py310haa95532_0
  - multidict=6.0.2=py310h2bbff1b_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.5=py310haa95532_0
  - nbclient=0.5.13=py310haa95532_0
  - nbconvert=6.5.4=py310haa95532_0
  - nbformat=5.9.2=py310haa95532_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - networkx=3.1=py310haa95532_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - notebook=6.5.4=py310haa95532_1
  - notebook-shim=0.2.2=py310haa95532_0
  - numexpr=2.8.7=py310h2cd9be0_0
  - numpy=1.26.0=py310h055cbcc_0
  - numpy-base=1.26.0=py310h65a83cf_0
  - oauthlib=3.2.2=py310haa95532_0
  - opencv=4.6.0=py310ha36de5b_5
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=1.1.1w=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.1=py310haa95532_0
  - pandas=2.1.1=py310h4ed8f06_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h78c2152_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py310h045eedc_0
  - pixman=0.40.0=h2bbff1b_1
  - platformdirs=3.10.0=py310haa95532_0
  - plotly=5.9.0=py310haa95532_0
  - ply=3.11=py310haa95532_0
  - poppler=22.12.0=h0bf3bde_3
  - poppler-data=0.4.11=haa95532_1
  - prometheus_client=0.14.1=py310haa95532_0
  - prompt-toolkit=3.0.36=py310haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protobuf=3.20.3=py310hd77b12b_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=1.7.3=py310haa95532_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310haa95532_1
  - pyjwt=2.4.0=py310haa95532_0
  - pyopenssl=23.2.0=py310haa95532_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pyrsistent=0.18.0=py310h2bbff1b_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.11=h966fe2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python-graphviz=0.20.1=py310haa95532_0
  - python-json-logger=2.0.7=py310haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py310haa95532_0
  - pywin32=305=py310h2bbff1b_0
  - pywinpty=2.0.10=py310h5da7b33_0
  - pyyaml=6.0=py310h2bbff1b_1
  - pyzmq=23.2.0=py310hd77b12b_0
  - qt-main=5.15.2=h6072711_9
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtconsole=5.4.2=py310haa95532_0
  - qtpy=2.2.0=py310haa95532_0
  - qtwebkit=5.212=h2bbfb41_5
  - re2=2022.04.01=hd77b12b_0
  - regex=2023.10.3=py310h2bbff1b_0
  - requests=2.31.0=py310haa95532_0
  - requests-oauthlib=1.3.0=py_0
  - rfc3339-validator=0.1.4=py310haa95532_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.2.2=py310hd77b12b_0
  - scipy=1.11.3=py310h309d312_0
  - seaborn=0.12.2=py310haa95532_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py310haa95532_0
  - sip=6.6.2=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h6c2663c_0
  - sniffio=1.2.0=py310haa95532_1
  - soupsieve=2.5=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=8.2.2=py310haa95532_0
  - tensorboard=2.10.0=py310haa95532_0
  - tensorboard-data-server=0.6.1=py310haa95532_0
  - tensorboard-plugin-wit=1.8.1=py310haa95532_0
  - tensorflow=2.10.0=mkl_py310hd99672f_0
  - tensorflow-base=2.10.0=mkl_py310h6a7f48e_0
  - tensorflow-estimator=2.10.0=py310haa95532_0
  - termcolor=2.1.0=py310haa95532_0
  - terminado=0.17.1=py310haa95532_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tokenizers=0.13.3=py310h49fca51_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310haa95532_0
  - tornado=6.3.3=py310h2bbff1b_0
  - tqdm=4.65.0=py310h9909e9c_0
  - traitlets=5.7.1=py310haa95532_0
  - transformers=4.24.0=py310haa95532_0
  - typing-extensions=4.7.1=py310haa95532_0
  - typing_extensions=4.7.1=py310haa95532_0
  - tzdata=2023c=h04d1e81_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.16=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=0.58.0=py310haa95532_4
  - werkzeug=2.2.3=py310haa95532_0
  - wheel=0.41.2=py310haa95532_0
  - widgetsnbextension=4.0.5=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - winpty=0.4.3=4
  - wrapt=1.14.1=py310h2bbff1b_0
  - xgboost=1.7.3=py310haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - y-py=0.5.9=py310hb6bf4ef_0
  - yaml=0.2.5=he774522_0
  - yarl=1.8.1=py310h2bbff1b_0
  - ypy-websocket=0.8.2=py310haa95532_0
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - anykeystore==0.2
      - audioread==3.0.1
      - cloudpickle==1.6.0
      - colorlog==6.7.0
      - commonmark==0.9.1
      - cryptacular==1.6.2
      - cython==3.0.8
      - fastnlp==1.0.1
      - future==0.18.3
      - greenlet==3.0.3
      - gym==0.17.3
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - hupper==1.12.1
      - lazy-loader==0.3
      - librosa==0.7.1
      - llvmlite==0.41.1
      - minepy==1.2.6
      - monotonic-align==0.0.0
      - msgpack==1.0.7
      - numba==0.58.1
      - opencv-contrib-python==4.8.1.78
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.8.1.78
      - pastedeploy==3.1.0
      - pbkdf2==1.3
      - pip==23.3.2
      - plaster==1.1.2
      - plaster-pastedeploy==1.0.1
      - pooch==1.8.0
      - prettytable==3.9.0
      - py-cpuinfo==9.0.0
      - pygame==2.1.3
      - pyglet==1.5.0
      - pyramid==2.0.2
      - pyramid-mailer==0.15.1
      - python3-openid==3.2.0
      - ray==2.6.3
      - repoze-sendmail==4.4.1
      - resampy==0.4.2
      - rich==11.2.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - sqlalchemy==2.0.25
      - supervision==0.16.0
      - texttable==1.7.0
      - thop==0.1.1-2209072238
      - torch==2.1.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - transaction==4.0
      - translationstring==1.4
      - ultralytics==8.0.216
      - velruse==1.1.1
      - venusian==3.1.0
      - webob==1.8.7
      - wtforms==3.1.2
      - wtforms-recaptcha==0.3.2
      - zope-deprecation==5.0
      - zope-interface==6.1
      - zope-sqlalchemy==3.1
